apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('login/<int:pk>/', views.OTPLogin.as_view(), name='second_login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('duplicate/<int:pk>/', views.pass_duplicate, name='duplicate'),

]

facecup/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls'), name="accounts"),
    path('team', include('apps.team.urls'), name="team")
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models/user.py
import os

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.files.storage import FileSystemStorage
from apps.team.models.team import Team
from facecup import settings

RESUME_FILE_PATH = 'files/resume/admins'


class User(AbstractUser):
    team = models.OneToOneField(Team, on_delete=models.CASCADE, null=True, related_name='uteam')
    file_resume = models.FileField(upload_to=RESUME_FILE_PATH, null=True)

    class Meta:
        db_table = 'User'

    def __str__(self):
        return str(self.first_name)

    """
    Django requires that custom users define their own Manager class. By
    inheriting from `BaseUserManager`, we get a lot of the same code used by
    Django to create a `User`. 

    All we have to do is override the `create_user` function which we will use
    to create `User` objects.
    """

apps/team/models/team.py
from django.db import models
from common.validators import mobile_validator, mobile_length_validator, FARSI_LANGUAGE, EN_LANGUAGE

CODE_PATH = 'files/resume/codes'


class Team(models.Model):
    en_name = models.CharField(max_length=50, unique=True, validators=[EN_LANGUAGE])
    fa_name = models.CharField(max_length=50, unique=True, validators=[FARSI_LANGUAGE])
    phone = models.CharField(null=True, max_length=11, unique=True,
                             validators=[mobile_validator, mobile_length_validator])
    code = models.FileField(upload_to=CODE_PATH, null=True)

    verify_phone = models.BooleanField(default=False)

    class Meta:
        db_table = "Team"

    def __str__(self):
        return str(self.en_name)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('accounts:team', args=[self.id])

apps/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class UserLoginForm(forms.Form):
    en_name = forms.CharField(max_length=23)
    remember_me = forms.BooleanField(required=False)


class UserOTPForm(forms.Form):
    code = forms.CharField(max_length=4)

apps/accounts/views.py
from random import randint

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as django_logout
from django.contrib.auth.decorators import login_required
from django.core.cache import cache

from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.views import View

from common.utilities import set_otp_cache
from .forms import *
from apps.team.forms import TeamRegisterForm
from apps.team.models import Team

User = get_user_model()


def register(request):
    """Create and return a `Team` with an english name(en_name), persian name(fa_name) and phone."""
    if request.method == 'POST':
        team_form = TeamRegisterForm(request.POST)
        if team_form.is_valid():
            data = team_form.cleaned_data
            team = Team.objects.create(fa_name=data['fa_name'], en_name=data['en_name'], phone=data['phone'])
            phone = team.phone
            code = randint(1000, 9999)
            print(code)
            set_otp_cache(team.id, code)
            messages.success(request, 'رمز عبور یکبار مصرف ارسال شد', 'success')
            # send_smd(code, phone)
            return redirect('accounts:second_login', team.id)
        else:
            messages.error(request, 'لطفا اطلاعات صحیح وارد کنید', 'secondary')
            return render(request, 'accounts/register.html', {'team_form': team_form})

    else:
        team_form = TeamRegisterForm()

    context = {'team_form': team_form}
    return render(request, 'accounts/register.html', context)


class OTPLogin(View):
    """class for insert OTP and then if pass is correct,login team admin"""

    def get(self, request, pk):
        team = get_object_or_404(Team, id=pk)
        form = UserOTPForm()
        return render(request, 'accounts/second_login.html', {'form': form, 'pk': pk, 'phone_number': team.phone})

    def post(self, request, pk):
        url = request.META.get('HTTP_REFERER')
        form = UserOTPForm(request.POST)
        if form.is_valid():
            team = Team.objects.get(id=pk)
            validated_data = form.cleaned_data
            cache_team = cache.get(key=team.id)
            if cache_team is not None:
                if validated_data['code'] == cache_team['code']:
                    if len(User.objects.filter(team=team)) != 0:
                        user = User.objects.get(team=team)
                        authenticate(request, username=user.username, password=user.password)
                        login(request, user)
                        team.verify_phone = True
                        team.save()
                        return redirect('team:home')
                    else:
                        user = User(username=team.en_name, team=team)
                        user.set_password('1234')
                        user.save()
                        authenticate(request, username=user.username, password=user.password)
                        login(request, user)
                        # ??????????????????????????????????????????????????????????????????????????????????????????
                        return redirect('team:home')

                else:
                    messages.error(request, 'کد وارد شده صحیح نیست', 'danger')
                    return redirect(url)
            else:
                messages.error(request, 'کد منقضی شده است', 'warning')
                return redirect(url)
        else:
            messages.error(request, 'اطلاغات وارد شده نادرست می باشد.', 'secondary')
            return redirect(url)


def pass_duplicate(request, pk):
    """ this function send OTP again in second_login html page"""
    team = Team.objects.get(id=pk)
    phone = team.phone
    code = randint(1000, 9999)
    print(code)
    set_otp_cache(team.id, code)
    messages.success(request, 'رمز عبور یکبار مصرف ارسال شد', 'success')
    # send_smd(code, phone)
    return redirect('accounts:second_login', pk=team.id)


class Login(View):
    """
    this class enable team admin to login with phone number
    and then send a otp that admin must insert this code in
    another page that name is OTPLogin
    """

    def post(self, request):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user_name = data['en_name']
            if Team.objects.filter(en_name=user_name).count() == 0:
                messages.success(request, 'تیم با این نام موجود نیست لطفا ابتدا ثبت نام کنید', 'warning')
                return redirect('accounts:login')
            team = Team.objects.get(en_name=user_name)
            phone = team.phone
            code = randint(1000, 9999)
            print(code)
            set_otp_cache(team.id, code)
            # send_smd(code, phone)
            return redirect('accounts:second_login', pk=team.id)
        else:
            messages.success(request, 'اطلاعات وارد شده نادرست است', 'secondary')
            return render(request, 'accounts/login.html', {'form': form})

    def get(self, request):
        form = UserLoginForm()
        return render(request, 'accounts/login.html', {'form': form})


@login_required(login_url='login')
def user_logout(request):
    django_logout(request)
    messages.success(request, 'با موفقیت خارج شدید', 'success')
    return redirect('accounts:login')

apps/accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <title>ورود</title>
    <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body dir="rtl">
<div class="login-face-cup d_flex">
    <div class="d_flex content">
        <div class="register-image"></div>
        <div class="login-form">
            <h2 class="title">ورود</h2>
            <div class="line"></div>
            <form action="{% url 'accounts:login' %}" method="POST" class="login-form">
                {% csrf_token %}
                {% if messages %}
                    {% for msg in messages %}
                        <div class="info otp-warning" id="hideMeWarning">
                            {{ msg }}
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="login-input">
                    <input type="text" name="en_name" maxlength="23" required="" id="id_en_name" placeholder=" "
                           autocomplete="off">
                    <span>نام کاربری (نام لاتین تیم)</span>
                    <img id="en_name_img" src="{% static 'accounts/img/email icon.png' %}" alt="">
                </div>

                {#                <input type="checkbox" name="remember_me" id="id_remember_me">#}
                {#                <span>مرا بخاطر بسپار</span>#}

                <button type="submit" class="login-btn">
                    <span>وارد شوید</span>
                </button>
            </form>
            <span>هنوز حساب کاربری ندارید؟ <a href="{% url 'accounts:register' %}">ثبت نام کن</a></span>
        </div>

    </div>

</div>
<script src="{% static 'accounts/js/jquery.min.js' %}"></script>
<script>
    $(function () {

        $("#id_en_name").focus(function () {
            $("#en_name_img").hide();

        }).blur(function () {
            $("#en_name_img").show();
        });

    });
</script>
</body>
</html>

apps/accounts/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>ثبت نام</title>
    <link rel="stylesheet" href="{% static 'accounts/css/register.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body dir="rtl">
<div class="sign-in-face-cup d_flex">
    <div class="d_flex content ">
        <div class="register-form ">
            <h2 class="title">ثبت نام</h2>
            {% if messages %}
                {% for msg in messages %}
                    <div class="error-messages">{{ msg }}</div>
                {% endfor %}
            {% endif %}
            <form action="{% url 'accounts:register' %}" method="POST" class="register-form-info">
                {% csrf_token %}
                <div class="register-input">
                    <input type="text" name="en_name" maxlength="50" required="" id="id_en_name" placeholder=" "
                           autocomplete="off">
                    <span>نام تیم (لاتین)</span>
                    <img id="en_name_img" src="{% static 'accounts/img/email icon.png' %}" alt="">
                </div>
                <p id="en_name_disc" class="disc">نام لاتین به‌عنوان نام کاربری شما جهت ورود به سیستم درنظر گرفته خواهد
                    شد</p>
                <div class="register-input">
                    <input type="text" name="fa_name" maxlength="50" required="" id="id_fa_name" placeholder=" "
                           autocomplete="off">
                    <span>نام تیم (فارسی)</span>
                    <img id="fa_name_img" src="{% static 'accounts/img/email icon.png' %}" alt="">
                </div>
                <div class="register-input">
                    <input type="text" name="phone" maxlength="11" required="" id="id_phone"
                           placeholder=" " autocomplete="off" class="disc">
                    <span>شماره موبایل</span>
                    <img id="phone_img" src="{% static 'accounts/img/mobile icon.png' %}" alt="">
                </div>
                <p id="phone_disc" class="disc">کدفعالسازی و احراز هویت به این شماره ارسال خواهد شد</p>

                <p class="text" style="margin-top: 80px">شما با ثبت نام در فیس‌کاپ، <span class="bold">شرایط استفاده از خدمات </span>را
                    می‌پذیرید
                </p>
                <button type="submit" class="register-btn">
                    <span> ثبت نام</span>
                </button>
                <p class="text">قبلاً ثبت نام کرده‌اید؟<a href="{% url 'accounts:login' %}" class="bold">وارد شوید</a>
                </p>

            </form>

        </div>
        <div class="register-image"></div>
    </div>
</div>
<script src="{% static 'accounts/js/jquery.min.js' %}"></script>
<script>
    $(function () {

        $("#id_en_name").focus(function () {
            $("#en_name_disc").show();
            $("#en_name_img").hide();
            $("#id_en_name").attr("placeholder", "تنها حروف و فاصله مجاز است");
        }).blur(function () {
            $("#en_name_disc").hide();
            $("#en_name_img").show();
            $("#id_en_name").attr("placeholder", " ");
        });

    });
    $(function () {

        $("#id_fa_name").focus(function () {
            $("#fa_name_img").hide();
        }).blur(function () {
            $("#fa_name_img").show();
        });

    });
    $(function () {

        $("#id_phone").focus(function () {
            $("#phone_disc").show();
            $("#phone_img").hide();
            $("#id_phone").attr("placeholder", "مثال: 09121234567");
        }).blur(function () {
            $("#phone_disc").hide();
            $("#phone_img").show();
            $("#id_phone").attr("placeholder", " ");
        });

    });
</script>
</body>
</html>

apps/accounts/templates/accounts/second_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <title>فعال سازی</title>
    <link rel="stylesheet" href="{% static 'accounts/css/otp.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body dir="rtl">
<div class="login-face-cup d_flex">
    <div class="d_flex content">
        <div class="otp-form">
            <h2 class="title">رمز یکبار مصرف</h2>


            <form action="" class="otp-form" method="POST">
                <div class="otp_message">
                    {% if messages %}
                        {% for msg in messages %}
                            {% if msg.tags == 'danger error' %}
                                <div class="info otp-error" id="hideMeError">
                                    کد وارد شده صحیح نیست
                                </div>
                            {% elif msg.tags == 'warning error' %}
                                <div class="info otp-warning" id="hideMeWarning">
                                    کد منقضی شده است
                                </div>
                            {% elif msg.level_tag == 'success' %}
                                <div class="info otp-info" id="hideMeInfo">
                                    رمز عبور یکبار مصرف به شماره <span class="phone-number">{{ phone_number }}</span>
                                    ارسال
                                    شد
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
                {% csrf_token %}
                <div class="otp-input">
                    <input type="text" name="code" maxlength="4" required="" id="id_code" placeholder=" "
                           autocomplete="off">
                    <span>رمز عبور یکبار مصرف</span>
                    <img id="clock_img" src="{% static 'accounts/img/lock.png' %}" alt="">
                </div>
                <button type="submit" class="otp-btn">
                    <span> ورود</span>
                </button>

            </form>
            <div>
                <a href="{% url 'accounts:duplicate' pk %}" class="link" style="margin-left: 15px">ارسال مجدد کد</a>
            </div>
        </div>
        <div class="register-image"></div>
    </div>
</div>
<script src="{% static 'accounts/js/jquery.min.js' %}"></script>
<script>
    $(function () {

        $("#id_code").focus(function () {
            $("#clock_img").hide();

        }).blur(function () {
            $("#clock_img").show();
        });

    });
</script>
</body>
</html>