apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('login/<int:pk>/', views.OTPLogin.as_view(), name='second_login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('duplicate/<int:pk>/', views.pass_duplicate, name='duplicate'),

]

apps/team/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'team'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('get_content/', views.get_content, name='get_content'),
    path('frequently_question/', views.frequently_question, name='frequently_question'),
    path('profile/', views.team_update, name='team_profile'),
    path('result/', views.result, name='result'),
    path('sent_code/', views.sent_code, name='sent_code'),
    path('add/', views.add_member, name='add_member'),
    path('get_members/', views.get_members, name='get_members'),
    path('user/<pk>/delete', views.remove_member, name='remove'),
    path('user/<pk>', views.get_member, name='get_member'),
    path('user/<pk>/edit', views.team_user_update, name='update_member'),
    path('sendcode/', views.send_code, name='send_code'),

]

facecup/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls'), name="accounts"),
    path('team', include('apps.team.urls'), name="team")
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/team/models/frequently_questions.py
from django.db import models


class FrequentlyQuestions(models.Model):
    question = models.TextField()
    answer = models.TextField()

    def __str__(self):
        return str(self.id) + self.question

apps/team/models/rules.py
from django.db import models


class Rules(models.Model):
    file = models.FileField(upload_to='media/Rules', null=True)

apps/team/models/sponsor.py
from django.db import models


class Sponsor(models.Model):
    s_name = models.CharField(max_length=50)
    logo = models.ImageField(upload_to='media\logo')
    kind = models.CharField(max_length=50)

    class Meta:
        db_table = "Sponsor"

    def __str__(self):
        return self.s_name

apps/team/models/team.py
from django.db import models
from common.validators import mobile_validator, mobile_length_validator, FARSI_LANGUAGE, EN_LANGUAGE

CODE_PATH = 'files/resume/codes'


class Team(models.Model):
    en_name = models.CharField(max_length=50, unique=True, validators=[EN_LANGUAGE])
    fa_name = models.CharField(max_length=50, unique=True, validators=[FARSI_LANGUAGE])
    phone = models.CharField(null=True, max_length=11, unique=True,
                             validators=[mobile_validator, mobile_length_validator])
    code = models.FileField(upload_to=CODE_PATH, null=True)

    verify_phone = models.BooleanField(default=False)

    class Meta:
        db_table = "Team"

    def __str__(self):
        return str(self.en_name)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('accounts:team', args=[self.id])

apps/team/models/team_user.py
from django.db import models

from apps.team.models.team import Team
from common.validators import FARSI_LANGUAGE

RESUME_FILE_PATH = 'files/resume/team_user'


class TeamUser(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='mteam')
    first_name = models.CharField(max_length=100, validators=[FARSI_LANGUAGE])
    last_name = models.CharField(max_length=100, validators=[FARSI_LANGUAGE])
    file_resume = models.FileField(upload_to=RESUME_FILE_PATH)

    class Meta:
        db_table = "TeamUser"
        unique_together = [['team', 'first_name', 'last_name']]

    def __str__(self):
        return str(self.first_name)

apps/team/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth import get_user_model

User = get_user_model()

from apps.team.models.team import Team
from apps.team.models.team_user import TeamUser
from common.validators import FARSI_LANGUAGE


class TeamRegisterForm(ModelForm):
    class Meta:
        model = Team
        fields = ['en_name', 'fa_name', 'phone']


class MemberTeamForm(ModelForm):
    class Meta:
        model = TeamUser
        fields = ['first_name', 'last_name', 'file_resume']


class AdminTeamForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'file_resume')
    # first_name = forms.CharField(max_length=20, validators=[FARSI_LANGUAGE])
    # last_name = forms.CharField(max_length=25, validators=[FARSI_LANGUAGE])
    # file_resume = forms.FileField(required=False)


class CodeForm(ModelForm):
    class Meta:
        model = Team
        fields = ['id', 'code']

apps/team/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import FileResponse, JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from .forms import MemberTeamForm, TeamRegisterForm, AdminTeamForm, CodeForm
from .models import Rules, TeamUser, FrequentlyQuestions

User = get_user_model()


@login_required(login_url='login')
def home(request):
    team = request.user.team
    return render(request, 'team/home.html', {'team': team})


@login_required(login_url='login')
def team_profile(request):
    team = request.user.team
    member = TeamUser.objects.filter(team=team)
    return render(request, 'team/profile.html', {'team': team, 'member': member})


@login_required(login_url='login')
def frequently_question(request):
    team = request.user.team
    questions = FrequentlyQuestions.objects.all()
    return render(request, 'team/frequently_questions.html', {'team': team, 'questions': questions})


@login_required(login_url='login')
def result(request):
    team = request.user.team
    return render(request, 'team/result.html', {'team': team})


@login_required(login_url='login')
def get_content(request):
    team = request.user.team
    return render(request, 'team/get_content.html', {'team': team})


@login_required(login_url='login')
def sent_code(request):
    team = request.user.team
    return render(request, 'team/code.html', {'team': team, "file_name": team.code})


@login_required(login_url='login')
def team_update(request):
    """this function update team profile that consist of member team,admin team and team specifications"""
    team = request.user.team
    member = TeamUser.objects.filter(team=team)
    user = User.objects.get(pk=request.user.id)
    if request.method == 'POST':
        team_form = TeamRegisterForm(request.POST, instance=team)
        member_form = MemberTeamForm(request.POST)
        admin_form = AdminTeamForm(request.POST, request.FILES, instance=user)
        if team_form.is_valid() and admin_form.is_valid():
            team_form.save()
            admin_form.save()
            messages.success(request, 'به روز رسانی انجام شد', 'success')
            return redirect('team:team_profile')
        else:
            messages.error(request, 'به دلیل اطلاعات نادرست به روز رسانی انجام نشد', 'warning')
            return redirect('team:team_profile')

    else:
        team_form = TeamRegisterForm(instance=request.user.team)
        member_form = MemberTeamForm()
        admin_form = AdminTeamForm(instance=user)
        context = {'team': team, 'members': member, 'team_form': team_form, 'member_form': member_form,
                   'admin_form': admin_form, 'admin': request.user}
        return render(request, 'team/profile.html', context)


@csrf_exempt
@login_required(login_url='accounts:login')
def add_member(request):
    """this function is for add team member that needs first name,last name and CV"""
    team = request.user.team
    member_count = team.mteam.all().count()
    if request.method == 'POST':
        print("add member")
        if member_count < 5:
            form = MemberTeamForm(request.POST, request.FILES)
            if form.is_valid():
                data = form.cleaned_data
                if not TeamUser.objects.filter(first_name=data['first_name'], last_name=data['last_name'], team=team):
                    team_user = TeamUser.objects.create(team=team, first_name=data['first_name'],
                                                        last_name=data['last_name'],
                                                        file_resume=data['file_resume'])
                    return JsonResponse(
                        {'id': team_user.id, 'fulname': team_user.first_name + ' ' + team_user.last_name,
                         'member_count': team.mteam.count()})
                else:
                    return HttpResponseBadRequest('عضو تیم قبلا اضافه شده است')
            else:
                return HttpResponseBadRequest('اطلاعات وارد شده صحیح نمی باشد')

        else:
            return HttpResponseBadRequest('مجاز به اضافه کردن بیش از 5 نفر نیستید')


@login_required(login_url='accounts:login')
def get_members(request):
    if request.method == 'GET':
        team = request.user.team
        # members = {'{}'.format(member.id): {'full_name': member.first_name + ' ' + member.last_name} for member in
        #            team.mteam.all()}
        members = {'count': team.mteam.count()}
        return JsonResponse(members)


@csrf_exempt
@login_required(login_url='login')
def remove_member(request, pk):
    if request.method == "DELETE":
        team = request.user.team
        print("delete memeber")
        member = get_object_or_404(TeamUser, pk=pk)
        member.delete()
        return JsonResponse({"member_count": team.mteam.count(), 'data': 'کاربر با موفقیت حذف شد'})


@login_required(login_url='login')
def get_member(request, pk):
    if request.method == "GET":
        print('get member')
        member = get_object_or_404(TeamUser, pk=pk)
        return JsonResponse(
            {"id": member.id, "first_name": member.first_name, "last_name": member.last_name,
             "file_name": member.file_resume.name.split('/')[-1]})


@csrf_exempt
@login_required(login_url='login')
def team_user_update(request, pk):
    if request.method == "POST":
        print("update member")
        member = get_object_or_404(TeamUser, pk=pk)
        member_form = MemberTeamForm(request.POST or None, request.FILES, instance=member)
        if member_form.is_valid():
            member_form.save()
            return JsonResponse({"id": member.id, "first_name": member.first_name, "last_name": member.last_name, })
        else:
            return HttpResponseBadRequest('اطلاعات وارد شده صحیح نمی باشد')


@csrf_exempt
@login_required(login_url='accounts:login')
def send_code(request):
    if request.method == 'POST':
        print(request.FILES)
        team = request.user.team
        form = CodeForm(request.FILES)
        if form.is_valid():
            team.code = form.cleaned_data['code']
            team.save()
    print(team.code)
    return JsonResponse({"code_name": team.code.name})

apps/team/templates/team/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "team/css/base.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    {% block css %}{% endblock %}
</head>
<body dir="rtl">
<div class="header">
    <img src="{% static 'team/img/base/Mask Group 3@2x.png' %}" style="width: 80px;height: 70px;z-index: 1" alt="">
    <div class="team">
        <div class="menu-icon"></div>
        <span>{{ team.fa_name }}</span>
        <ul>
            <li><a href="{% url 'team:team_profile' %}">پروفایل</a></li>
            <li><a href="{% url 'accounts:logout' %}">خروج از حساب کاربری</a></li>
        </ul>
    </div>

</div>
<div style="display: flex">
    <div class="sidebar">
        <ul class="list">
            <li id="home"><a href="{% url 'team:home' %}"><img src="{% static "team/img/base/Icon material-home.svg" %}"
                                                               alt=""><span>خانه</span></a></li>
            <li id="profile"><a href="{% url 'team:team_profile' %}"><img src="{% static "team/img/base/profile.svg" %}"
                                                                          alt=""><span>پروفایل</span></a>
            </li>
            <li id="download"><a href="{% url 'team:get_content' %}"><img
                    src="{% static "team/img/base/Icon feather-download.svg" %}" alt=""><span>دریافت محتوا</span></a>
            </li>
            <li id="code"><a href="{% url "team:sent_code" %}"><img src="{% static "team/img/base/code svg.svg" %}"
                                                                    alt=""><span>ارسال کد</span></a></li>
            <li id="static"><a href="{% url "team:result" %}"><img src="{% static "team/img/base/static.svg" %}" alt=""><span>نتایج</span></a>
            </li>
            <li id="support"><a href=""><img src="{% static "team/img/base/support.svg" %}" alt=""><span>پشتیبانی</span></a>
            </li>
        </ul>
        <ul class="list" id="last-ul">
            <li id="frequently_question"><a href="{% url 'team:frequently_question' %}"><img
                    src="{% static "team/img/base/Icon awesome-question.svg" %}"
                    alt=""><span>سؤالات متداول</span></a></li>
            <li><a href="{% url 'accounts:logout' %}"><img src="{% static "team/img/base/Icon awesome-power-off.svg" %}"
                                                           alt=""><span>خروج</span></a></li>
        </ul>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

apps/team/templates/team/code.html
{% extends 'team/base.html' %}
{% load static %}
{% block title %}ارسال کد{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'team/css/code.css' %}">
{% endblock %}
{% block content %}
    <h2>ارسال کد</h2>
    <form id="send-code" enctype="multipart/form-data">
        <div class="d-flex file-box" style="color: #6c6c76">
            <span>فایل داکر</span>
            <div class="file-place" style="color: #6c6c76">
                <input type="file" name="file_resume" id="id_file_resume">
                <p id="file-p">برای انتخاب فایل کلیک کنید</p>
                <img src="{% static "team/img/profile/Icon metro-upload.png" %}" width="24px" alt="">
                <button type="submit" id="send_code_btn" hidden></button>
            </div>
        </div>
    </form>
    <div class="after-load d-flex-box">
        <div class="right d-flex-right">
            <img src="{% static "team/img/code/Icon feather-file.svg" %}" width="25px" height="32px" alt="">
            <div class="d-flex-left" style="margin-right: 15px">
                <span id="file_name">file_name.tar</span>
                <span class="date">23:11 - 1400/04/21</span>
            </div>
        </div>
        <div class="left d-flex-left">
            <img src="{% static "team/img/code/Icon material-delete.svg" %}" width="12px" height="16px"
                 style="margin-bottom: 10px" alt="">
            <img src="{% static "team/img/code/Icon material-autorenew.svg" %}" width="12px" height="16px" alt="">
        </div>

    </div>
    <h4 class="font attention">توجه:</h4>
    <p class="font description">
        فایل انتخابی باید با فرمت <span class="font attention">tar.</span> باشد<br>
        تا قبل از ساعت ۲۴<span class="font attention"> تاریخ روز ۱۴ بهمن ماه ۱۴۰۰</span> می‌توانید به دفعات کد خود را
        حذف و ویرایش نمایید<br>
        آخرین کد شما جهت ارزیابی مورد بررسی قرار می‌گیرد <br>
    </p>
    <script src="{% static 'accounts/js/jquery.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('#id_file_resume').change(function () {
                document.getElementById("send_code_btn").click();
            });
        });
    </script>
    {#    send file#}
    <script>
        $("#send-code").submit(function (e) {
            e.preventDefault();
            var formData = new FormData(this);
            $.ajax({
                type: 'POST',
                url: "{% url 'team:send_code' %}",
                data: formData,
                success: function (data) {
                    $("#file_name").text(data['code_name'])
                },
                error: function (data) {
                    console.log("no")
                },
                cache: false,
                contentType: false,
                processData: false
            });
        })

    </script>
{% endblock %}

apps/team/templates/team/frequently_questions.html
{% extends 'team/base.html' %}
{% load static %}
{% block title %}سوالات متداول{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'team/css/frequently_questions.css' %}">
{% endblock %}
{% block content %}
    <h2>سؤالات متداول</h2>
    {% for question in questions %}
        <div class="question-box">
            <div class="font question d-flex ">
                <img class="image" src="{% static "team/img/frequestly_question/Icon awesome-question (1).svg" %}" width="20px"
                     height="20px" alt="">
                {{ question.question }}
            </div>

            <div class="answer font d-flex">
                <img class="image" src="{% static "team/img/frequestly_question/Icon awesome-lightbulb.svg" %}" width="20px"
                     height="20px" alt="">
                <span style="font-size: 14px">{{ question.answer }}</span>
            </div>
        </div>
    {% endfor %}
{% endblock %}

apps/team/templates/team/get_content.html
{% extends 'team/base.html' %}
{% load static %}
{% block title %}دریافت محتوا{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'team/css/get_content.css' %}">
{% endblock %}
{% block content %}
    <h2>دریافت محتوای مسابقه</h2>
    <p class="p1">فایل‌های راهنما و دیتاست‌های نمونه جهت آزمایش:</p>
    <div class="example">
        <span><a href="{% static "team/file/dotfile.dot" %}" download="dotfile.dot">دریافت دیتاست نمونه اول</a></span>
        <span><a href="{% static "team/file/dotfile.dot" %}" download="dotfile.dot">دریافت دیتاست نمونه دوم</a></span>
        <span><a href="{% static "team/file/dotfile.dot" %}" download="dotfile.dot">دریافت داکرهای تست</a></span>
    </div>
    <p class="p1">نصب و اجرای داکرهای تست </p>
    <p class="explain">برای نصب داکر مراحل لینک زیر دنبال شود <br>

        https://docs.docker.com/engine/install/ <br>

        در صورتی که از سیستم عامل غیر از ویندوز استفاده می‏شود، باید docker compose نیز از لینک زیر نصب شود. در نسخه
        ویندوزی به صورت پیش فرض docker compose نصب شده
        است. <br>

        https://docs.docker.com/compose/install/ <br>

        همچنین برای اجرای اسکریپت‏های مورد نیاز در سیستم عامل ویندوز، باید از مسیر زیر git نصب شود.

        <br> https://git-scm.com/downloads <br>

        پس از نصب موارد بالا، در داخل پوشه docker راست کلیک نموده، سپس بر روی git bash here کلیک کرده و درون صفحه باز
        شده اسکریپت docker.sh را همانند شکل زیر اجرا
        نمایید.
    </p>
    <div class="d-flex">
        <img class="docker-img" src="{% static "team/img/get_content/img.png" %}" alt="">
    </div>
    <p class="explain">توجه نمایید که به جای team_name باید اسم لاتین تیم (که در سایت ثبت‎‌نام کرده ‏اید) و به جای
        team_pass باید شماره
        موبایل سرگروه تیم را وارد کنید. با این کار در MongoDB پایگاه داده‏ای با نام کاربری اسم تیم و رمز عبور شماره
        موبایل سرگروه ساخته می‎شود. این امر جهت ارزیابی نتایج الگوریتم شما بسیار حائز اهمیت است چرا که تیم داوری به
        داده ‏های شما با همین نام کاربری و رمز عبور دسترسی خواهد یافت. <br>

        در صورت بروز هر گونه مشکل در وارد کردن این موارد می‎توانید دستور زیر را اجرا کرده و سپس دستور start را دوباره
        اجرا نمایید.

        <br> ./docker.sh stop <br>

        برای اطمینان از اجرای درست ایمیج‌ها، می‏توانید با استفاده از مرورگر سیستم خود آدرس‎های زیر را باز کنید.

        <br>http://localhost/images/gallery/images.txt <br>

        http://localhost/images/probe/images.txt <br>

        در این دو آدرس نام تمام فایل‏های عکس probe و gallery آمده است. برای مشاهده هر عکس با داشتن اسم آن می‏توانید از
        آدرس‏های زیر استفاده کنید.

        <br>http://localhost/images/gallery/S000001.jpg <br>

        http://localhost/images/probe/S000029.jpg <br>
    </p>
    <h3>یک نمونه کد تست جهت کار با داکرها</h3>
    <p class="explain">در صورت موفقیت در تست مرحله قبل، می ‏توانید کد خود را برای کار با ایمیج‌‍‌ها بنویسید. جهت راحتی
        شما، در پوشه
        نکسترا تست یک نمونه کد پایتون برایبرقراری ارتباط با پایگاه داده ها و دریافت عکس ها نوشته شده است</p>
    <div class="d-flex">
        <img class="docker-img2" src="{% static "team/img/get_content/img_1.png" %}" alt="">
    </div>
    <p class="explain">
        برای اجرای این کد باید نکات زیر لحاظ شود :<br>

        در خط 9 به جای nextera_db باید اسم لاتین تیم و به جای 1199 باید شماره موبایل سرگروه تیم وارد شود. <br>

        کد فوق بر روی ماشین شما اجرا می‌شود. برای نسخه نهایی کد باید localhost را در خط 8 به mongodb و در خطوط 14 و 17
        به nginx تغییر دهید و برای ساخت ایمیج نهایی از کد خود و ارسال به مسابقه نیز نباید از localhost استفاده شود.
        بنابراین برای حالت تست و بررسی از localhost استفاده کنید و برای ساخت ایمیج نهایی، localhost را در خط 8 به
        mongodb و در خطوط 14 و 17 به nginx تغییر دهید. <br>

        قبل از اجرای کد تست، دستور زیر را اجرا نمایید تا پیش‎نیاز‎های کد نصب شوند. فرض شده است که پایتون نسخه 2 یا 3
        قبلا بر روی سیستم شما نصب شده است.

        <br>pip install -r requirements.txt
    </p>
    <h3>تهیه داکر از موتور خودتان جهت ارسال برای مسابقه</h3>
    <p class="explain">بعد از این که کد خود را نوشتید باید آن را در قالب داکر ایمیج برای مسابقه ارسال کنید. برای ساخت
        داکر ایمیج باید یک
        Dockerfile فایل نوشته شود. در پوشه nextera_test یک نمونه Dockerfile برای ساخت داکر ایمیج وجود دارد.</p>
    <div class="d-flex">
        <img class="docker-img3" src="{% static "team/img/get_content/img_2.png" %}" alt="">
    </div>
    <p class="explain" >
        دستور FROM مشخص می‏کند ایمیج از چه ایمیجی پایه‏ای ساخته خواهد شد یا اصطلاحا ایمیج بیس ایمیج جدید چه چیزی باشد.
        در این مثال چون کد نمونه به زبان پایتون نوشته شده است، از ایمیج بیس python:3 استفاده شده است. از طریق آدرس
        https://hub.docker.com می‏توانید ایمیج بیس مورد نیاز خود را پیدا نمایید.
        <br>
        دستور WORKDIR یک دایرکتوری در /usr کانتینر به وجود می‏آورد. همچنین داخل کانتینر دایرکتوری را به همین دایرکتوری
        ساخته شده تغییر می‎دهد و از آن به بعد تمام کار‌ها در این دایرکتوری انجام می‎شود.
        <br>
        دستور COPY فایل requirements.txt را در آدرس /. کپی می‎نماید. این فایل برای نصب پیش‎نیاز‌های اجرای کد لازم است.
        <br>
        دستور RUN برای اجرای دستورات به کار می‏رود. به عنوان مثال، پیش‎نیاز‎ها با اجرای دستور زیر بر روی داکر ایمیج نصب
        می‏شوند.
        <br>
        <span>pip install --no-cache-dir -r requirements.txt</span>
        <br>
        دستور CMD برای اجرای فرمان‌های داکر در زمان آغاز به کار آن است. در مثال فوق، می‌خواهیم وقتی داکر ایمیج اجرا شد،
        اسکریپت ما با استفاده از پایتون اجرا شود.
        <br>
        بعد از تکمیل فایل داکر، برای ساخت داکر ایمیج لازم است دستور زیر را در پوشه شامل فایل داکر اجرا نماییم.
        <br>
        <span>docker build --tag nextera_test /path/to/dockerfile</span>
        <br>
        شما به هنگام ساخت داکر ایمیج باید به جای nextera_test از اسم لاتین تیم خود استفاده نمایید تا اسم داکر ایمیج اسم
        تیم خودتان باشد.
        <br>
        سپس برای اجرای داکر ایمیج خود و ساخته شدن یک کانتینر می‌توانید از دستورات زیر استفاده نمایید.
        <br>
        حالت تست و آزمایشی (در سیستم خودتان). توجه کنید که در این حالت باید از localhost در کد پایتون خود جهت اتصال به
        سرور و دیتابیس استفاده کنید.
        <br>
        <span>docker run --name nextera_test1 --network host -d nextera_test</span>
        <br>
        ساخت ایمیج نهایی و بررسی و ثبت آن. این حالت زمانی است که شما نتایج خود را در حالت تست، نهایی کردید و قصد ساخت
        ایمیج نهایی را دارید. برای ساخت ایمیج نهایی، localhost را برای اتصال به سرور به nginx و برای اتصال به دیتابیس به
        mongodb تغییر دهید.
        <br>
        <span>docker run --name nextera_test1 --network docker_default -d nextera_test</span>
        <br>
        باید بجای nextera_test از اسم تیم خود استفاده نمایید. همچنین می‏توانید به جای nextera_test1 از یک اسم دلخواه
        استفاده نمایید. از اجرای این دستورات برای بررسی درست بودن داکر ایمیج خود استفاده نمایید.
        <br>
        انتظار ما این است که پس از اجرای این دستور برنامه شما درون کانتینر اجرا شده تصاویر را از nginx گرفته و هر یک از
        تصاویر probe را با تمام تصاویر gallery مقایسه نماید و نتیجه مقایسه را درون پایگاه داده‏ای به نام اسم تیم شما در
        MongoDB وارد نماید. نمونه کد مربوطه در شکل بخش دوم آمده است.
        <br>
        فراموش نکنید که برای دسترسی به nginx بر روی سیستم خود از آدرس localhost و پورت 80 استفاده نمایید و برای دسترسی
        به MongoDB از آدرس localhost و پورت 27017 استفاده نمایید.
        <br>
        نهایتا برای ذخیره کردن ایمیج نهایی خود به صورت یک فایل از دستور زیر استفاده کنید.
        <br>
        <span>docker save -o team_name.tar team_name</span>
        <br>
        مقادیر team_name را با نام تیم خود جایگزین کنید. اجرای دستور فوق یک فایل با نام team_name.tar در محل فعلی ایجاد
        می‌کند که در آن ایمیج team_name ذخیره شده است. بعد از آرگومان –o می‌توانید آدرس دلخواهی برای ذخیره ایمیج تعیین
        کنید.
    </p>
{% endblock %}

apps/team/templates/team/result.html
{% extends 'team/base.html' %}
{% load static %}
{% block title %}نتایج{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'team/css/result.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static "team/css/flipdown.css" %}">
    <script type="text/javascript" src="{% static "team/js/result/flipdown.js" %}"></script>
    <script type="text/javascript" src="{% static "team/js/result/main.js" %}"></script>
{% endblock %}
{% block content %}
    <div class="wrapper">
        <div id="flipdown" class="flipdown"></div>
    </div>
{% endblock %}